CREATE TABLE "RFIELD"."MOVIE" (
	"ID" NUMBER,
	"PRICE" NUMBER,
	"TITLE" VARCHAR2(120 BYTE)
	);

CREATE TABLE "RFIELD"."MOVIE_SHADOW" (
	"ID" NUMBER,
	"PRICE" NUMBER,
	"TITLE" VARCHAR2(120 BYTE)
	);
